container:
  image: apon77/aosp:cirrus
  cpu: 8
  memory: 16G

build-task:
    show_script:
      - repo init --depth=1 -u git://github.com/aex-tmp/manifest.git -b 12.x -g default,-mips,-darwin,-notdefault
      - git clone https://github.com/me-abhiroop/local_manifest.git --depth 1 -b main .repo/local_manifests
      - repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j8
      - source build/envsetup.sh
      - lunch aosp_vince-userdebug
      - m aex
